//-----------------------------------------------------------------------------
// <copyright file="PlanningState.generated.cs" company="Ciena Corporation"\>
//     Copyright (c) Ciena Corporation. All rights reserved.
// </copyright\>
//
// This file was generated by a tool. Do not make modifications to this file.
//
//-----------------------------------------------------------------------------

namespace OnepMini.V1.Etp.Common
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>Planning State</summary>
    public partial class PlanningState
    {
        private string _planningStatus;
        private string _planningSource;
        private string _planningTimestamp;
        private OnepMini.V1.Etp.Common.PlanningPhase _planningPhase;

    	/// <summary>
        /// Initializes a new instance of the <see cref="PlanningState"/> class.
        /// </summary>
        public PlanningState()
    	{
        }

        [System.Runtime.Serialization.IgnoreDataMember]
        [JsonIgnore]
        public virtual long OId { get; set; }


        /// <summary>Planning State</summary>
        [JsonProperty("planningStatus", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual string PlanningStatus
        {
            get { return _planningStatus; }
            set 
            {
                if (_planningStatus != value)
                {
                    _planningStatus = value; 
                }
            }
        }

        /// <summary>Planning Source</summary>
        [JsonProperty("planningSource", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual string PlanningSource
        {
            get { return _planningSource; }
            set 
            {
                if (_planningSource != value)
                {
                    _planningSource = value; 
                }
            }
        }

        /// <summary>Planning Timestamp</summary>
        [JsonProperty("planningTimestamp", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual string PlanningTimestamp
        {
            get { return _planningTimestamp; }
            set 
            {
                if (_planningTimestamp != value)
                {
                    _planningTimestamp = value; 
                }
            }
        }

        /// <summary>Planning Phase</summary>
        [JsonProperty("planningPhase", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual OnepMini.V1.Etp.Common.PlanningPhase PlanningPhase
        {
            get { return _planningPhase; }
            set 
            {
                if (_planningPhase != value)
                {
                    _planningPhase = value; 
                }
            }
        }


    }
}