//-----------------------------------------------------------------------------
// <copyright file="ReportingMetaInfo.generated.cs" company="Ciena Corporation"\>
//     Copyright (c) Ciena Corporation. All rights reserved.
// </copyright\>
//
// This file was generated by a tool. Do not make modifications to this file.
//
//-----------------------------------------------------------------------------

namespace OnepMini.V1.Etp.Common
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>Metainfo for reporting APIs</summary>
    public partial class ReportingMetaInfo
    {
        private long? _pageSize;
        private long? _pageNumber;
        private long? _totalRecordsInReport;
        private long? _totalRecordsInDB;

    	/// <summary>
        /// Initializes a new instance of the <see cref="ReportingMetaInfo"/> class.
        /// </summary>
        public ReportingMetaInfo()
    	{
        }

        [System.Runtime.Serialization.IgnoreDataMember]
        [JsonIgnore]
        public virtual long OId { get; set; }


        /// <summary>Number of records in one page of report</summary>
        [JsonProperty("pageSize", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual long? PageSize
        {
            get { return _pageSize; }
            set 
            {
                if (_pageSize != value)
                {
                    _pageSize = value; 
                }
            }
        }

        /// <summary>Page number for this report</summary>
        [JsonProperty("pageNumber", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual long? PageNumber
        {
            get { return _pageNumber; }
            set 
            {
                if (_pageNumber != value)
                {
                    _pageNumber = value; 
                }
            }
        }

        /// <summary>The total number of records in this page</summary>
        [JsonProperty("totalRecordsInReport", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual long? TotalRecordsInReport
        {
            get { return _totalRecordsInReport; }
            set 
            {
                if (_totalRecordsInReport != value)
                {
                    _totalRecordsInReport = value; 
                }
            }
        }

        /// <summary>The total number of records in the database</summary>
        [JsonProperty("totalRecordsInDB", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual long? TotalRecordsInDB
        {
            get { return _totalRecordsInDB; }
            set 
            {
                if (_totalRecordsInDB != value)
                {
                    _totalRecordsInDB = value; 
                }
            }
        }


    }
}