//-----------------------------------------------------------------------------
// <copyright file="ReportingInfra.generated.cs" company="Ciena Corporation"\>
//     Copyright (c) Ciena Corporation. All rights reserved.
// </copyright\>
//
// This file was generated by a tool. Do not make modifications to this file.
//
//-----------------------------------------------------------------------------

namespace TopologyRestLibrary.V1.Etp.Reports
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>ReportingInfra</summary>
    public partial class ReportingInfra
    {
        private string _projectId;
        private FibersReport _fibersReport;

    	/// <summary>
        /// Initializes a new instance of the <see cref="ReportingInfra"/> class.
        /// </summary>
        public ReportingInfra()
    	{
        }

        [System.Runtime.Serialization.IgnoreDataMember]
        [JsonIgnore]
        public virtual long Id { get; set; }


        /// <summary>Project Id</summary>
        [JsonProperty("projectId", Required = Required.Always)]
        public virtual string ProjectId
        {
            get { return _projectId; }
            set 
            {
                if (_projectId != value)
                {
                    _projectId = value; 
                }
            }
        }

        /// <summary>FibersReport</summary>
        [JsonProperty("fibersReport", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual FibersReport FibersReport
        {
            get { return _fibersReport; }
            set 
            {
                if (_fibersReport != value)
                {
                    _fibersReport = value; 
                }
            }
        }


    }
}