//-----------------------------------------------------------------------------
// <copyright file="ReportingRoot.generated.cs" company="Ciena Corporation"\>
//     Copyright (c) Ciena Corporation. All rights reserved.
// </copyright\>
//
// This file was generated by a tool. Do not make modifications to this file.
//
//-----------------------------------------------------------------------------

namespace TopologyRestLibrary.V1.Etp.Reports
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>ReportingRoot</summary>
    public partial class ReportingRoot
    {
        private string _projectId;
        private DateTimeOffset? _creationDate;
        private DateTimeOffset? _lastAccessedDate;
        private TopologyRestLibrary.V1.Etp.Reports.FibersReport _fibersReport;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportingRoot"/> class.
        /// </summary>
        public ReportingRoot()
        {
        }

        [System.Runtime.Serialization.IgnoreDataMember]
        [JsonIgnore]
        public virtual long OId { get; set; }


        /// <summary>Project Id. Null indicates that the report is marked for delete</summary>
        [JsonProperty("projectId", Required = Required.Always)]
        public virtual string ProjectId
        {
            get { return _projectId; }
            set 
            {
                if (_projectId != value)
                {
                    _projectId = value; 
                }
            }
        }

        /// <summary>Creation date of this report</summary>
        [JsonProperty("creationDate", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? CreationDate
        {
            get { return _creationDate; }
            set 
            {
                if (_creationDate != value)
                {
                    _creationDate = value; 
                }
            }
        }

        /// <summary>Date when this report was last accessed</summary>
        [JsonProperty("lastAccessedDate", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? LastAccessedDate
        {
            get { return _lastAccessedDate; }
            set 
            {
                if (_lastAccessedDate != value)
                {
                    _lastAccessedDate = value; 
                }
            }
        }

        /// <summary>FibersReport</summary>
        [JsonProperty("fibersReport", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public virtual TopologyRestLibrary.V1.Etp.Reports.FibersReport FibersReport
        {
            get { return _fibersReport; }
            set 
            {
                if (_fibersReport != value)
                {
                    _fibersReport = value; 
                }
            }
        }


    }
}