//-----------------------------------------------------------------------------
// <copyright file="UrlParameter.generated.cs" company="Ciena Corporation"\>
//     Copyright (c) Ciena Corporation. All rights reserved.
// </copyright\>
//
// This file was generated by a tool. Do not make modifications to this file.
//
//-----------------------------------------------------------------------------

namespace TopologyRestLibrary.V1.Etp.Reports
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>UrlParameter</summary>
    public partial class UrlParameter
    {
        private string _name;
        private string _value;

        /// <summary>
        /// Initializes a new instance of the <see cref="UrlParameter"/> class.
        /// </summary>
        public UrlParameter()
        {
        }

        [System.Runtime.Serialization.IgnoreDataMember]
        [JsonIgnore]
        public virtual long OId { get; set; }


        /// <summary>Parameter name.</summary>
        [JsonProperty("name", Required = Required.Always)]
        public virtual string Name
        {
            get { return _name; }
            set 
            {
                if (_name != value)
                {
                    _name = value; 
                }
            }
        }

        /// <summary>Parameter value.</summary>
        [JsonProperty("value", Required = Required.Always)]
        public virtual string Value
        {
            get { return _value; }
            set 
            {
                if (_value != value)
                {
                    _value = value; 
                }
            }
        }


    }
}