//-----------------------------------------------------------------------------
// <copyright file="ModellingStatus.generated.cs" company="Ciena Corporation"\>
//     Copyright (c) Ciena Corporation. All rights reserved.
// </copyright\>
//
// This file was generated by a tool. Do not make modifications to this file.
//
//-----------------------------------------------------------------------------

namespace OnepMini.V1.Common
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>ModellingStatus</summary>
    public enum ModellingStatus
    {
    #pragma warning disable 1591
         [EnumMember(Value = "Full")]
    	 Full, 
         [EnumMember(Value = "Preliminary")]
    	 Preliminary, 
    #pragma warning restore 1591
    }
}